name: TVBox Merge

on: workflow_dispatch

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: leexuben/BINGO-TV
          path: bingo-tv
          token: ${{ secrets.GH_TOKEN }}

      - run: |
          cd bingo-tv
          echo '{"sites":[]}' > 综合影视.json
          echo "✅ 已创建空文件"
