name: TVBox Complete Merge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  complete-merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: leexuben/BINGO-TV
        path: bingo-tv
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Merge all sites
      run: |
        python << 'EOF'
        import json
        import requests
        
        # 源文件配置
        sources = [
            {
                "name": "王二小",
                "url": "https://raw.githubusercontent.com/leexuben/TV-BOX/main/tvbox/王二小/api.json",
                "jar": "https://raw.githubusercontent.com/leexuben/TV-BOX/main/tvbox/王二小/spider.jar",
                "base": "https://raw.githubusercontent.com/leexuben/TV-BOX/main/tvbox/王二小/"
            },
            {
                "name": "潇洒", 
                "url": "https://raw.githubusercontent.com/leexuben/TV-BOX/main/tvbox/潇洒/api.json",
                "jar": "https://raw.githubusercontent.com/极狐/leexuben/TV-BOX/main/tvbox/潇洒/spider.jar",
                "base": "https://raw.githubusercontent.com/leexuben/TV-BOX/main/tvbox/潇洒/"
            },
            {
                "name": "巧技",
                "url": "https://raw.githubusercontent.com/leexuben/TV-BOX/main/tvbox/巧技/api.json",
                "jar": "https://raw.githubusercontent.com/leexuben/TV-BOX/main/tvbox/巧技/spider.jar",
                "base": "https://raw.githubusercontent.com/leexuben/TV-BOX/main/tvbox/巧技/"
            },
            {
                "name": "影视",
                "url": "https://raw.githubusercontent.com/leexuben/ljlfct01.github.io/main/影视",
                "jar": "https://raw.githubusercontent.com/leexuben/ljlfct01.github.io/main/jar/spider.jar",
                "base": "https://raw.githubusercontent.com/leexuben/ljlfct01.github.io/main/"
            }
        ]
        
        target_file = "bingo-tv/综合影视.json"
        
        def get_sites(url):
            try:
                response = requests.get(url, timeout=30)
                if response.status_code == 200:
                    content = response.text
                    try:
                        data = json.loads(content)
                        if isinstance(data, dict) and 'sites' in data:
                            return data['sites']
                        elif isinstance(data, list):
                            return data
                    except:
                        start = content.find('{')
                        end = content.rfind('}') + 1
                        if start != -1 and end != -1:
                            data = json.loads(content[start:end])
                            if isinstance(data, dict) and 'sites' in data:
                                return data['sites']
                            elif isinstance(data, list):
                                return data
                return []
            except:
                return []
        
        # 读取目标文件
        try:
            with open(target_file, 'r', encoding='utf-8') as f:
                target_data = json.load(f)
        except:
            target_data = {}
        
        if 'sites' not in target_data:
            target_data['sites'] = []
        
        existing_sites = target_data['sites']
        existing_keys = {site.get('key', '') for site in existing_sites}
        
        # 从每个源文件获取数据
        for source in sources:
            sites = get_sites(source['url'])
            for site in sites:
                # 为站点添加正确的jar
                if 'jar' not in site:
                    site['jar'] = source['jar']
                
                # 修复相对路径
                if 'api' in site and isinstance(site['api'], str) and site['api'].startswith('./'):
                    site['api'] = source['base'] + site['api'][2:]
                
                if 'ext' in site and isinstance(site['ext'], str) and site['ext'].startswith('./'):
                    site['ext'] = source['base'] + site['ext'][2:]
                
                # 去重添加
                key = site.get('key', '')
                if key and key not in existing_keys:
                    existing_sites.append(site)
                    existing_keys.add(key)
        
        target_data['sites'] = existing_sites
        
        # 保存文件
        with open(target_file, 'w', encoding='utf-8') as f:
            json.dump(target_data, f, ensure_ascii=False, indent=2)
        EOF

    - name: Check result
      run: |
        cd bingo-tv
        if [ -f "综合影视.json" ]; then
          python3 -c "
import json
with open('综合影视.json', 'r') as f:
    data = json.load(f)
sites = data.get('sites', [])
print(f'合并后站点数量: {len(sites)}')
if sites:
    print('前3个站点的jar字段:')
    for i, site in enumerate(sites[:3]):
        jar = site.get('jar', '无jar')
        key = site.get('key', '无key')
        name = site.get('name', '无name')
        print(f'  {i+1}. {name} (key: {key})')
        print(f'     jar: {jar[:60]}...')
"
        else
          echo "文件不存在"
        fi

    - name: Commit changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd bingo-tv
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add 综合影视.json
        if git diff --cached --quiet; then
          echo "没有检测到更改"
          exit 0
        fi
        git commit -m "Merge: Complete sites update $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin main
        echo "更改已提交"
